### ISSUE TITLE
exception when running mrf->optimize

### ISSUE THREAD

**Issue by kevin-kaixu** [chaowang15/RGBDPlaneDetection#1]
Hi,
I found the code always generates an exception when running mrf refinement.
Specifically, the exception is triggered in this function:
Graph::flowtype Graph::maxflow()
{
 ...
if (a_for->r_rev_cap)
}
where a_for is a NULL pointer.

Have you ever encountered this issue? Would you please give me some clue?

Thanks!

ps. I have set the cam. intrinsics correctly.

**Comment by chaowang15** [comment]
The code works very well in my place. Actually I got similar problem but in some other project instead of this one. I think the bug is from the MRF code which usually causes weird memory overflow on large dataset in Visual Studio, but works better in Linux. You can test your code there to see if it works.

**Comment by kevin-kaixu** [comment]
Thanks for your prompt reply!
OK, let me test it in Linux and see.

**Comment by YihuanL** [comment]
I have the same issue of this, so is there any method to solve this? thank you in advance.

**Comment by chaowang15** [comment]
> I have the same issue of this, so is there any method to solve this? thank you in advance.



> I have the same issue of this, so is there any method to solve this? thank you in advance.

**Comment by chaowang15** [comment]
> I have the same issue of this, so is there any method to solve this? thank you in advance.

I tried to fix it before but failed, since the bug is from the MRF code and hard to find. In my place, MRF code only works in Visual Studio 2010 in Windows and crashes in 2013 or later, but works fine under gcc/g++ in Ubuntu 16.

**Comment by YihuanL** [comment]
Got it, Thank you

**Comment by daijicheng** [comment]
I think the reason is that the sizeof(long) is different in gcc and windows. After I added the marco USE_64_BIT_PTR_CAST and changed the #define PTR_CAST long to long long, it just worked in vs 2015.

**Comment by johntranz** [comment]
@daijicheng it working on vs 2019 no ? you can give more detailed instructions
