### ISSUE TITLE
large numbers of image sequences 

### ISSUE THREAD

**Issue by doki3003** [chaowang15/RGBDPlaneDetection#2]
Hi,

I have noticed that when I'm processing image sequences with release mode, it crashes after a while, and the plane-data is incorrect (the segment result is right). I have tested it in windows 10 and ubuntu. It is correct with a single image, but it fails to deal with image sequences (I mean the plane-data, especially the pixel numbers of plane ). The debug mode can work with image sequences, but the speed is very slow and almost stop after 100 images. So I wonder it may be some memory bug. Would you please test with image sequences? I think 10 images is enough. By the way, I didn't use MRF.

Thank you!

**Comment by chaowang15** [comment]
Yes let me test it in my place and reply you soon.

**Comment by chaowang15** [comment]
It works pretty well in my computer. I am using Visual Studio 2010 and tested on a sequence with over 4000 frames with 640x480 resolution of both color and depth image. Without MRF it will be very fast at about 20 fps including data I/O time. With MRF it is much slower at about 7 seconds for each frame. Just updated the repo and provide a script file for you to refer if you want.

**Comment by doki3003** [comment]
Thank you! I will try it later.
