### ISSUE TITLE
Small modifications required for linux 

### ISSUE THREAD

**Issue by joanpepcompany** [chaowang15/RGBDPlaneDetection#3]
Hello, 
First of all, thank you very much to share your code. 
In order that your code runs in Ubuntu, I had to done two small modifications:
On one hand, I had to add the Makefile on the include/MRF2.2 that you can find in the following library link (http://vision.middlebury.edu/MRF/code/). 
On the other hand, you wrote in the readme.txt file that the following command is required to use the package: 

> RGBDPlaneDetection <-o> color_image depth_image

 however, the arguments required in the main.cpp are almost 4, where you need to add the output path, for example, I use the directory path:

>  RGBDPlaneDetection <-o> color_image depth_image .

Thanks again!

**Comment by chaowang15** [comment]
> Hello,
> First of all, thank you very much to share your code.
> In order that your code runs in Ubuntu, I had to done two small modifications:
> On one hand, I had to add the Makefile on the include/MRF2.2 that you can find in the following library link (http://vision.middlebury.edu/MRF/code/).
> On the other hand, you wrote in the readme.txt file that the following command is required to use the package:
> 
> > RGBDPlaneDetection <-o> color_image depth_image
> 
> however, the arguments required in the main.cpp are almost 4, where you need to add the output path, for example, I use the directory path:
> 
> > RGBDPlaneDetection <-o> color_image depth_image .
> 
> Thanks again!

I just noticed that the repo ignored the Makefile format, and that's why there is no MakeFile in the MRF2.2 code. And I also didn't notice about the usage in the readme. Will update it soon. Thanks for your update! Appreciate it very much.
